/* eslint-disable max-len */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/jsx-filename-extension */
/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable import/no-unresolved */
/* eslint-disable no-unused-vars */
import Head from 'next/head';
import Image from 'next/image';
import Header from 'components/Header';
import Footer from 'components/Footer';
import Product from 'components/Product';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div className="header w-full flex flex-col justify-between items-center">
          <div className="container flex flex-col justify-center h-full py-12">
            <div className="self-center items-center justify-between flex flex-col sm:flex-row w-full md:w-5/6 xl:w-full px-4 sm:px-0">
              <div className="w-full text-center sm:text-left sm:w-1/2 py-12 sm:px-8">
                <h1 className="tracking-wide text-yellow-400 text-2xl mb-6">
                  TÌM ĐỒ THẤT LẠC
                  {' '}
                  <span className="text-gray-800 font-bold tracking tracking-widest">
                    TRỰC TUYẾN
                  </span>
                </h1>
                <h2 className="font-bold tracking-widest text-4xl">
                  Bạn là sinh viên
                </h2>
                <span className="content__container block font-light text-browngray text-2xl my-6">
                  <ul className="content__container__list">
                    <li className="content__container__list__item xl:pl-3">
                      bạn đã từng đánh rơi những vật dụng  cá nhân quan trọng
                    </li>
                  </ul>
                </span>
                <p className="font-bold tracking-widest text-4xl">
                  Không sao cả, hãy đến với “timdothatlacvku.com”
                </p>
              </div>
              <div className="w-full xl:w-4/6 sm:w-1/2">
                <img
                  src="/images/Mar-Business_2.jpg"
                  alt="AWE.SOME header"
                />
              </div>
            </div>
          </div>
          <div className="flex flex-row w-full justify-center pb-12">
            <a
              className="px-10 py-2 text-white bg-yellow-400 rounded-full shadow-md text-lg hover:bg-yellow-500 hover:border-red"
              href="#about"
            >
              More Information
            </a>
          </div>
        </div>
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-wrap w-full mb-20">
              <div className="lg:w-1/2 w-full mb-6 lg:mb-0">
                <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
                  Latest news
                </h1>
                <div className="h-1 w-20 bg-yellow-500 rounded" />
              </div>
            </div>
            <Product />
          </div>
        </section>

        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-wrap w-full mb-20">
              <div className="lg:w-1/2 w-full mb-6 lg:mb-0">
                <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
                  Testimonial
                </h1>
                <div className="h-1 w-20 bg-yellow-500 rounded" />
              </div>
            </div>
            <div className="flex flex-wrap -m-4">
              <div className="lg:w-1/3 lg:mb-0 mb-6 p-4">
                <div className="h-full text-center">
                  <img
                    alt="testimonial"
                    className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                    src="/images/MIN01146.jpg"
                  />
                  <p className="leading-relaxed">
                    Website rất hữu dụng, thao tác nhanh, dễ tìm kiếm, dễ dàng hỗ trợ sinh viên những lúc để quên đồ dùng cá nhân tại trường.
                  </p>
                  <span className="inline-block h-1 w-10 rounded bg-yellow-500 mt-6 mb-4" />
                  <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                    NGUYỄN HOÀI LAM
                  </h2>
                  <p className="text-gray-500">Sinh viên</p>
                </div>
              </div>
              <div className="lg:w-1/3 lg:mb-0 mb-6 p-4">
                <div className="h-full text-center">
                  <img
                    alt="testimonial"
                    className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                    src="/images/MIN01243.jpg"
                  />
                  <p className="leading-relaxed">
                    Tôi rất thường xuyên để quên đồ dùng cá nhân tại trường, nhờ có website này mà tôi có thể nhận lại đồ của mình.
                  </p>
                  <span className="inline-block h-1 w-10 rounded bg-yellow-500 mt-6 mb-4" />
                  <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                    VÕ THỊ HOÀNG THƯ
                  </h2>
                  <p className="text-gray-500">Sinh viên</p>
                </div>
              </div>
              <div className="lg:w-1/3 lg:mb-0 p-4">
                <div className="h-full text-center">
                  <img
                    alt="testimonial"
                    className="w-20 h-20 mb-8 object-cover object-center rounded-full inline-block border-2 border-gray-200 bg-gray-100"
                    src="/images/avatar.jpeg"
                  />
                  <p className="leading-relaxed">
                    Là một sinh viên của nhà trường, sau khi sử dụng website này thì tôi thấy nó rất hữu ích, hi vọng nhà phát triển sẽ tối ưu và thêm nhiều chức năng hơn để thuận tiện cho viện tìm kiếm
                  </p>
                  <span className="inline-block h-1 w-10 rounded bg-yellow-500 mt-6 mb-4" />
                  <h2 className="text-gray-900 font-medium title-font tracking-wider text-sm">
                    Lê Thị Hoa
                  </h2>
                  <p className="text-gray-500">Sinh viên</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
